### ISSUE TITLE
"Force update" feature

### ISSUE THREAD

**Issue by orhanhenrik** [jpodwys/superagent-cache#20]
Hey! I have a project using this cool module right now, and I am in need of cache invalidation. To do this I am in need of forcing a request to actually execute instead of coming from cache. I don't think this should be hard to implement, and I am happy to code it if you think it's a good idea. I have looked at your `backgroundRefresh` functionality, but it is not feasible for the projects needs because the cache needs to be updated instantly whenever the server receives notification of updates.
I am thinking a syntax like this should work well and be similar to the other features in this module:

    request
        .get(....)
        .set(....)
        .forceUpdate(true)
        .end(....)

What do you think?

**Comment by jpodwys** [comment]
Would you mind providing a more detailed example? I'm interested in what causes the need to force an update for a key that has not expired. I can think of a couple of possible reasons, but I'd like to be familiar with your scenario.

**Comment by orhanhenrik** [comment]
There is a list of reviews that are cached on the server-side. Whenever a new review comes in we want the cache to get reloaded. The cache is needed because the data is hosted on Parse and we have a server that does rendering (react isomorphic). Whenever a new review comes in the server will get a notification, and it should then reload the specific url so the cache is up to date. `backgroundRefresh` is not feasible because the update needs to be quick, otherwise the user will not see his own review if he reloads the page. Also backgroundRefresh would lead to a lot of unnecessary bandwidth usage.

**Comment by jpodwys** [comment]
This sounds like it's functionally identical to one of my own use cases--a new resource comes in which does not automatically invalidate the cache key generated when retrieving the list because the list comes from a different URL. Does that sound like the same thing?

If so, I was hoping to solve it in a different way. I would like to provide some means of associating specific resources, such as /api/review, with a list of URLs, such as /api/reviews, such that when superagent-cache detects a POST, PUT, or DELETE to /api/review, it will automatically invalidate the cache key that was created when a GET was called at /api/reviews. 

If I can pull this off, then you wouldn't need to keep track of whether to call forceUpdate, it would just happen. I also think this could be a little simpler to deal with as more of these scenarios pop up within a single project. 

What do you think?

**Comment by orhanhenrik** [comment]
I don't think that will work, because the actual editing of the data is done inside a browser. The browser sends that data to Parse, and our server is notified of the change. So the server never modifies the data itself, and superagent-cache cannot know of the change. That's why I need to be able to refresh a cache "entry" manually. Not all changes to the data go through the node server and superagent-cache.

**Comment by jpodwys** [comment]
Ok, that makes sense. Just one more question--how is your server notified of the change?

**Comment by orhanhenrik** [comment]
That is still not implemented. Probably through a http request or a work queue. Is another function call in the chain like I demoed above a good format? If so, I will start working on it and make a PR :)

**Comment by jpodwys** [comment]
Yeah that sounds good. Sorry for all the questions, just wanted to make sure we're not solving the same problem multiple ways.

**Comment by orhanhenrik** [comment]
Of course :+1:

**Comment by orhanhenrik** [comment]
Submitted a PR here: https://github.com/jpodwys/superagent-cache/pull/34

**Comment by jpodwys** [comment]
This feature was published to npm in `1.4.0` with #34. Thanks!
