### ISSUE TITLE
1.5.0 not working with superagent-bluebird-promise

### ISSUE THREAD

**Issue by wikiwong** [jpodwys/superagent-cache#38]
The `then` function appears to implement different specs than superagent-bluebird-promise.  Specifically, I was not able to call `catch` on the return of `then`.  Any way to normalize this?  Sticking with 1.4.1 in the mean time.

**Comment by jpodwys** [comment]
Thank you for this note!

This issue arises because both libraries overwrite superagent's `.then` function. superagent-cache allows you to pass in an instance of superagent that may have already been patched, but superagent-bluebird-promise does not. The following are potential solutions:

1. Rename superagent-cache's `.then` function so there is no naming collision.
2. PR to superagent-bluebird-promise to make it so they allow passing in a pre-patched superagent instance. This would allow users to patch with superagent-cache first then with superagent-bluebird-promise second to get the behavior you're expecting.

What are your thoughts?

**Comment by jpodwys** [comment]
Not saying we shouldn't make a change to superagent-cache, but can't you also do the following:

```javascript
superagent
  .get('url')
  .promise().then(...)
```

Not the prettiest, but it would work with `1.5.0`.

**Comment by jpodwys** [comment]
I've just created the [superagent-bluebird-promise-compatability](https://github.com/jpodwys/superagent-cache/tree/superagent-bluebird-promise-compatability) branch. Please try it and let me know if it fixes the issue you're seeing.

**Comment by wikiwong** [comment]
@jpodwys Thanks for taking a look at this!  I pulled down that branch and it seems to fail still.  The `promise` property is undefined on Request.  I modified it locally to check `if (!Request.prototype.then)` and that is working for me.  Let me know what you think

**Comment by jpodwys** [comment]
OK good point, thanks!. I've [updated the branch](https://github.com/jpodwys/superagent-cache/compare/superagent-bluebird-promise-compatability?expand=1#diff-4dbf3418a42aeb6a71f9826fd3798172R109) with `if(!Request.prototype.promise)` rather than `if(!Request.prototype.then)` because superagent appears to have had `Request.prototype.then` populated [since mid 2015](https://github.com/visionmedia/superagent/commit/25bc045ea4ee298e550f617fef7b481919be6991).

The branch should now play nicely superagent-bluebird-promise and I'm willing to merge it into master if it solves the issue you're seeing.

However, this change is not necessary for superagent-cache to work with the majority of promisified superagent libs. The reason it already works with most other libs is that they accept a superagent instance to be modified. I'd really like to fix this correctly at some point by having superagent-bluebird-promise accept an optional superagent argument. I submitted an issue to their repo (it's linked above your most recent comment), but I didn't want to make you wait on their response.

Please let me know if the branch works for you. If so, I'll merge it and cut a new release.

**Comment by wikiwong** [comment]
Yup that branch is working for me.  Thanks @jpodwys !  Appreciate the responsiveness!

**Comment by jpodwys** [comment]
Published in `1.5.1`.
