### ISSUE TITLE
Ability to run as a plugin

### ISSUE THREAD

**Issue by jpodwys** [jpodwys/superagent-cache#51]
Currently, superagent-cache runs as a patch which means that all subsequent uses of superagent are also patched. A few different users have requested the ability to use superagent-cache as a plugin via superagent's `.use()` chainable. Perhaps I can add this functionality at some point.

**Comment by jpodwys** [comment]
Due to a number of people who have requested the ability to have `superagent-cache`'s features without globally patching superagent, I've created [`superagent-cache-plugin`](https://github.com/jpodwys/superagent-cache-plugin). There isn't currently any documentation available, but you can use it as follows:

```javascript
var superagent = require('superagent');
var cacheModule = require('cache-service-cache-module');
var cache = new cacheModule();
var superagentCache = require('superagent-cache-plugin')(cache);

superagent
  .get(uri)
  .use(superagentCache)
  .end(function (response){
    // Response is now cached
  }
);
```

I've tagged each of you in this issue because you've submitted issues in the past that could have benefited from a non-global version of `superagent-cache`. If you have time, I would appreciate you taking a look at it and letting me know what you think.

To anyone else who reads this issue, I'd appreciate any feedback.

@nim23 @vijayst @deyhle

**Comment by nim23** [comment]
@jpodwys This would definitely help the situation I was trying to solve. We had internal packages that came with their own version of `superagent` because of `superagent-cache`, which meant we had two different version of `superagent` in the final bundle, one that our project used and the other from an installed internal package. 

To optimise the build size I tried to alias `superagent` with a single version of `superagent` using `webpack` for the internal package and the app itself but `superagen-cache` ended up patching the `superagent` singleton itself. Although an edge case but for that scenario this is perfect.

Thanks!!

**Comment by jpodwys** [comment]
@nim23 Thanks for the response. I'll try to put together some documentation and get a release out to NPM. Perhaps then people in your situation can contact the maintainers of repos like the one you're using to ask them to consider switching from `superagent-cache` to `superagent-cache-plugin`.

**Comment by jpodwys** [comment]
As a note, `superagent-cache-plugin` currently does not include two functions present in `superagent-cache`: `preventDuplicateCalls` and `backgroundRefresh`. I'd like to add them, but I believe they're the least-used features and the hardest to test. I'll hope to add them into `superagent-cache`plugin` after its initial release.

**Comment by jpodwys** [comment]
OK I added docs and cut a `1.0.0` release of `superagent-cache-plugin` on NPM.

**Comment by vijayst** [comment]
Thanks @jpodwys.
